## 1. Imports
If an import fails, install the dependencies in this notebook's kernel with `%pip install requests beautifulsoup4 pandas numpy scipy`.

In [1]:
from pathlib import Path
import re
import time

import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup
from requests.adapters import HTTPAdapter
from scipy.stats import gaussian_kde
from urllib3.util.retry import Retry


from IPython.display import display

## 2. Hero lists and settings

In [2]:
vanguards = sorted([
    "Venom", "Emma Frost", "Magneto", "Doctor Strange", "The Thing", "Groot", "Hulk", "Thor", "Peni Parker",
    "Captain America", "Rogue", "Angela", "Deadpool Vanguard", "The Hood", "Devil Dinosaur"
])

duelists = sorted([
    "Moon Knight", "Squirrel Girl", "Human Torch", "Black Widow", "Namor", "The Punisher",
    "Hawkeye", "Scarlet Witch", "Psylocke", "Winter Soldier", "Wolverine", "Iron Man", "Hela",
    "Mister Fantastic", "Spider Man", "Iron Fist", "Star Lord", "Black Panther", "Storm", "Magik",
    "Phoenix", "Blade", "Daredevil", "Deadpool Duelist", "Cyclops", "Gorr The God Butcher", "Elsa Bloodstone",
    "Black Cat"
])

strategists = sorted([
    "Jeff The Land Shark", "Luna Snow", "Cloak & Dagger", "Invisible Woman", "Adam Warlock",
    "Loki", "Mantis", "Rocket Raccoon", "Gambit", "Ultron", "Deadpool Strategist", "Jubilee", "White Fox",
])

sorted_heroes = vanguards + duelists + strategists
BASE_URL = "https://rivalsmeta.com/characters/{}/matchups"
HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; OptimalRivalry/1.0)"}



REQUEST_DELAY = 0.5
REQUEST_TIMEOUT = 30
print(f"{len(sorted_heroes)} heroes: {len(vanguards)} vanguards, {len(duelists)} duelists, {len(strategists)} strategists")

56 heroes: 15 vanguards, 28 duelists, 13 strategists

## 3. Parsing helpers

In [3]:
def format_hero_name(hero_name):
    """Use the URL slug as identity, independent of punctuation/display names."""
    name = hero_name.lower().replace("&", " ")
    return re.sub(r"[^a-z0-9]+", "-", name).strip("-")


def parse_matchups(html, hero, heroes=None):
    """Read named columns, without depending on image classes or cell order."""
    heroes = sorted_heroes if heroes is None else list(heroes)
    names_by_slug = {format_hero_name(name): name for name in heroes}
    soup = BeautifulSoup(html, "html.parser")
    matchups = {}
    for table in soup.find_all("table"):
        headings = [th.get_text(" ", strip=True).casefold()
                    for th in table.select("thead th")]
        if not {"hero", "win rate", "matches"}.issubset(headings):
            continue
        hero_col, rate_col, matches_col = (
            headings.index(name) for name in ("hero", "win rate", "matches")
        )
        for row in table.select("tbody tr"):
            cells = row.find_all("td", recursive=False)
            if len(cells) <= max(hero_col, rate_col, matches_col):
                raise ValueError(f"{hero}: incomplete matchup row")
            hero_cell = cells[hero_col]
            link = hero_cell.find("a", href=re.compile(r"^/characters/"))
            if link:
                slug = link["href"].split("/")[2]
            else:
                img = hero_cell.find("img", alt=True)
                name = img["alt"] if img else hero_cell.get_text(" ", strip=True)
                slug = format_hero_name(name)
            opponent = names_by_slug.get(slug)
            if opponent is None:
                raise ValueError(f"{hero}: unknown opponent {slug!r}; update the hero lists")
            rate_text = cells[rate_col].get_text("", strip=True)
            count_text = re.sub(r"[,\s]", "", cells[matches_col].get_text(strip=True))
            if not re.fullmatch(r"\d+(?:\.\d+)?\s*%", rate_text):
                raise ValueError(f"{hero} vs {opponent}: invalid win rate {rate_text!r}")
            if not re.fullmatch(r"\d+", count_text):
                raise ValueError(f"{hero} vs {opponent}: invalid match count {count_text!r}")
            rate, count = float(rate_text.rstrip("%")), int(count_text)
            if not 0 <= rate <= 100 or count <= 0:
                raise ValueError(f"{hero} vs {opponent}: win rate/count out of range")
            if opponent in matchups:
                raise ValueError(f"{hero}: duplicate matchup for {opponent}")
            matchups[opponent] = (rate, count)

    missing = set(heroes) - {hero} - matchups.keys()
    if not matchups or missing:
        raise ValueError(
            f"{hero}: missing matchup data for {', '.join(sorted(missing)) or 'all heroes'}. "
            "The page may be unavailable or its layout may have changed."
        )
    # Preserve the original model's synthetic self-match convention.
    opponent_counts = [count for name, (_, count) in matchups.items() if name != hero]
    matchups[hero] = (50.0, int(np.mean(opponent_counts)))
    return matchups

## 4. Start a session and reset downloaded pages

In [4]:
if "session" in globals():
    session.close()
session = requests.Session()
session.headers.update(HEADERS)
retry = Retry(total=3, backoff_factor=1, status_forcelist=[429, 500, 502, 503, 504])
session.mount("https://", HTTPAdapter(max_retries=retry))
pages = {}
fetch_errors = {}
print("Session ready; page cache cleared.")

Session ready; page cache cleared.

## 5. Inspect one hero before downloading everything

In [5]:
test_hero = "Luna Snow"
assert test_hero in sorted_heroes, "Choose a hero from sorted_heroes"
test_url = BASE_URL.format(format_hero_name(test_hero))
response = session.get(test_url, timeout=REQUEST_TIMEOUT)
print(f"HTTP {response.status_code}: {response.url}")
response.raise_for_status()
test_html = response.text
pages[test_hero] = test_html
test_soup = BeautifulSoup(test_html, "html.parser")
print("Table headings:")
for table in test_soup.find_all("table"):
    print([th.get_text(" ", strip=True) for th in table.select("thead th")])

HTTP 200: https://rivalsmeta.com/characters/luna-snow/matchups
Table headings:
['Hero', 'Matchup', 'Win Rate', 'Difference', 'Matches']
['Hero', 'Matchup', 'Win Rate', 'Difference', 'Matches']
['Hero', 'Matchup', 'Win Rate', 'Difference', 'Matches']

In [6]:
test_matchups = parse_matchups(test_html, test_hero)
test_df = pd.DataFrame.from_dict(test_matchups, orient="index", columns=["Win Rate", "Matches"])
print(f"Parsed {len(test_matchups) - 1} opponents, plus the synthetic self-match.")
display(test_df)

Parsed 55 opponents, plus the synthetic self-match.

                      Win Rate  Matches
The Thing                51.74    28852
Deadpool Vanguard        49.22    22187
Emma Frost               48.93    73766
Magneto                  48.92    95663
The Hood                 47.48    60464
Doctor Strange           46.95    68303
Venom                    46.22    23801
Angela                   45.70    10785
Groot                    45.44    13260
Rogue                    45.38    20146
Thor                     45.28    23690
Hulk                     44.24    22975
Captain America          42.40    11722
Devil Dinosaur           41.11    36135
Peni Parker              31.66    12601
Squirrel Girl            58.36     6420
Phoenix                  54.83    10592
Cyclops                  54.38    19051
Namor                    52.06    32834
The Punisher             51.11    27408
Hawkeye                  51.10     6026
Moon Knight              50.96    14007
Black Panther            50.95    10627
Winter Soldier           50.45    60206
Black Widow              50.39    18252
Deadpool Duelist         50.25     9904
Blade                    49.07    11962
Star Lord                48.53    12730
Spider Man               47.73    33783
Black Cat                47.31     7616
Wolverine                47.26    14074
Elsa Bloodstone          47.03    21732
Mister Fantastic         47.02    10138
Iron Fist                46.35    24198
Iron Man                 45.78    10470
Hela                     45.73    45579
Psylocke                 45.48    27552
Scarlet Witch            45.42    41832
Gorr The God Butcher     45.03    53373
Daredevil                44.05    15922
Human Torch              43.96     8562
Magik                    42.35    23529
Storm                    41.68     6572
Cloak & Dagger           51.46    84187
Deadpool Strategist      50.96    24386
White Fox                50.69    41577
Invisible Woman          48.02    85192
Gambit                   47.53    53432
Jubilee                  47.49    70784
Jeff The Land Shark      47.45    28399
Adam Warlock             47.31     8740
Loki                     44.06    21891
Rocket Raccoon           43.51    54564
Ultron                   41.64    11085
Mantis                   41.12    22373
Luna Snow                50.00    29380

## 6. Download the remaining hero pages

In [7]:
fetch_errors = {}
for i, hero in enumerate(sorted_heroes, start=1):
    if hero in pages:
        continue
    time.sleep(REQUEST_DELAY)
    url = BASE_URL.format(format_hero_name(hero))
    print(f"Fetching {hero} ({i}/{len(sorted_heroes)})...", flush=True)
    try:
        response = session.get(url, timeout=REQUEST_TIMEOUT)
        response.raise_for_status()
        pages[hero] = response.text
    except requests.RequestException as exc:
        fetch_errors[hero] = str(exc)
        print(f"  FAILED: {exc}")

print(f"Cached {sum(hero in pages for hero in sorted_heroes)}/{len(sorted_heroes)} pages.")
if fetch_errors:
    display(pd.Series(fetch_errors, name="Request error").to_frame())

Fetching Angela (1/56)...
Fetching Captain America (2/56)...
Fetching Deadpool Vanguard (3/56)...
Fetching Devil Dinosaur (4/56)...
Fetching Doctor Strange (5/56)...
Fetching Emma Frost (6/56)...
Fetching Groot (7/56)...
Fetching Hulk (8/56)...
Fetching Magneto (9/56)...
Fetching Peni Parker (10/56)...
Fetching Rogue (11/56)...
Fetching The Hood (12/56)...
Fetching The Thing (13/56)...
Fetching Thor (14/56)...
Fetching Venom (15/56)...
Fetching Black Cat (16/56)...
Fetching Black Panther (17/56)...
Fetching Black Widow (18/56)...
Fetching Blade (19/56)...
Fetching Cyclops (20/56)...
Fetching Daredevil (21/56)...
Fetching Deadpool Duelist (22/56)...
Fetching Elsa Bloodstone (23/56)...
Fetching Gorr The God Butcher (24/56)...
Fetching Hawkeye (25/56)...
Fetching Hela (26/56)...
Fetching Human Torch (27/56)...
Fetching Iron Fist (28/56)...
Fetching Iron Man (29/56)...
Fetching Magik (30/56)...
Fetching Mister Fantastic (31/56)...
Fetching Moon Knight (32/56)...
Fetching Namor (33/56)...
Fetching Phoenix (34/56)...
Fetching Psylocke (35/56)...
Fetching Scarlet Witch (36/56)...
Fetching Spider Man (37/56)...
Fetching Squirrel Girl (38/56)...
Fetching Star Lord (39/56)...
Fetching Storm (40/56)...
Fetching The Punisher (41/56)...
Fetching Winter Soldier (42/56)...
Fetching Wolverine (43/56)...
Fetching Adam Warlock (44/56)...
Fetching Cloak & Dagger (45/56)...
Fetching Deadpool Strategist (46/56)...
Fetching Gambit (47/56)...
Fetching Invisible Woman (48/56)...
Fetching Jeff The Land Shark (49/56)...
Fetching Jubilee (50/56)...
Fetching Loki (51/56)...
Fetching Mantis (53/56)...
Fetching Rocket Raccoon (54/56)...
Fetching Ultron (55/56)...
Fetching White Fox (56/56)...
Cached 56/56 pages.

## 7. Parse cached pages into matrices

In [8]:
WinRate_df = pd.DataFrame(index=sorted_heroes, columns=sorted_heroes, dtype=float)
NumMatches_df = pd.DataFrame(index=sorted_heroes, columns=sorted_heroes, dtype=float)
parse_errors = {}
for hero in sorted_heroes:
    if hero not in pages:
        parse_errors[hero] = "Page not downloaded; retry section 6."
        continue
    try:
        matchups = parse_matchups(pages[hero], hero)
    except ValueError as exc:
        parse_errors[hero] = str(exc)
        continue
    for opponent, (rate, count) in matchups.items():
        WinRate_df.at[hero, opponent] = rate
        NumMatches_df.at[hero, opponent] = count

print(f"Parsed {len(sorted_heroes) - len(parse_errors)}/{len(sorted_heroes)} heroes.")
if parse_errors:
    display(pd.Series(parse_errors, name="Parse error").to_frame())
display(WinRate_df.head())
display(NumMatches_df.head())

Parsed 56/56 heroes.

,Angela,Captain America,Deadpool Vanguard,Devil Dinosaur,Doctor Strange,Emma Frost,Groot,Hulk,Magneto,Peni Parker,...,Gambit,Invisible Woman,Jeff The Land Shark,Jubilee,Loki,Luna Snow,Mantis,Rocket Raccoon,Ultron,White Fox
Angela,50.00,46.88,52.58,48.28,50.29,53.92,45.98,47.78,52.46,31.01,...,50.84,54.69,52.41,51.38,48.76,54.30,45.67,47.50,42.24,53.64
Captain America,53.13,50.00,56.99,47.49,53.10,55.51,51.89,52.74,55.20,38.52,...,53.78,55.08,55.00,53.42,49.44,57.60,49.26,50.52,48.21,57.30
Deadpool Vanguard,47.42,43.01,50.00,41.53,46.92,48.46,45.04,43.44,50.01,29.30,...,47.20,48.92,49.70,47.00,43.88,50.78,41.37,43.75,43.76,50.16
Devil Dinosaur,51.72,52.51,58.47,50.00,55.29,58.69,56.84,50.65,57.76,40.17,...,56.18,56.57,56.18,54.84,52.25,58.89,50.42,52.37,49.80,57.92
Doctor Strange,49.71,46.90,53.08,44.71,50.00,52.13,50.14,47.38,52.43,34.90,...,51.09,51.05,50.90,51.57,47.46,53.05,45.23,46.39,44.98,53.27

,Angela,Captain America,Deadpool Vanguard,Devil Dinosaur,Doctor Strange,Emma Frost,Groot,Hulk,Magneto,Peni Parker,...,Gambit,Invisible Woman,Jeff The Land Shark,Jubilee,Loki,Luna Snow,Mantis,Rocket Raccoon,Ultron,White Fox
Angela,5275.0,2208.0,3701.0,4841.0,11398.0,12499.0,2277.0,4278.0,14991.0,2512.0,...,10451.0,14787.0,4888.0,12125.0,3380.0,10785.0,3941.0,9455.0,1863.0,7446.0
Captain America,2208.0,5752.0,3929.0,6094.0,12696.0,13249.0,2251.0,5197.0,15641.0,2056.0,...,11633.0,13958.0,5189.0,13272.0,4086.0,11722.0,3672.0,10041.0,1958.0,9468.0
Deadpool Vanguard,3701.0,3929.0,9489.0,10399.0,21947.0,22041.0,4165.0,7065.0,29512.0,4344.0,...,19561.0,26675.0,9143.0,21775.0,7284.0,22187.0,6678.0,16325.0,3231.0,12468.0
Devil Dinosaur,4841.0,6094.0,10399.0,16003.0,32061.0,36824.0,6940.0,11126.0,41971.0,5835.0,...,33415.0,44189.0,16011.0,42319.0,12375.0,36135.0,12129.0,30186.0,5860.0,21941.0
Doctor Strange,11398.0,12696.0,21947.0,32061.0,30887.0,71399.0,14511.0,24735.0,94393.0,13539.0,...,68248.0,85785.0,28094.0,79817.0,22145.0,68303.0,21875.0,56322.0,11813.0,42206.0

## 8. Validate completeness and numeric ranges
If this fails, inspect the errors above and rerun the relevant download/parse cells. All 56 × 56 entries (including synthetic diagonals) must be present with the current roster.

In [9]:
def validate_matrices(win_rates, num_matches):
    for label, frame in (("Win rates", win_rates), ("Match counts", num_matches)):
        if list(frame.index) != sorted_heroes or list(frame.columns) != sorted_heroes:
            raise ValueError(f"{label}: unexpected hero labels/order")
        missing = frame.isna().sum(axis=1)
        if missing.any():
            raise ValueError(f"{label}: missing entries by hero: {missing[missing > 0].to_dict()}")
        if not np.isfinite(frame.to_numpy(dtype=float)).all():
            raise ValueError(f"{label}: non-finite values")
    if not ((win_rates >= 0) & (win_rates <= 100)).to_numpy().all():
        raise ValueError("Win rates must be between 0 and 100")
    counts = num_matches.to_numpy(dtype=float)
    if (counts <= 0).any() or (counts != np.floor(counts)).any():
        raise ValueError("Match counts must be positive integers")
    if not (np.diag(win_rates) == 50).all():
        raise ValueError("Self-match win rates must be 50%")

validate_matrices(WinRate_df, NumMatches_df)
NumMatches_df = NumMatches_df.astype("int64")
print(f"Validated {WinRate_df.shape[0]} × {WinRate_df.shape[1]} matrices; no missing values.")

Validated 56 × 56 matrices; no missing values.

## 9. Calculate the weighted KDE payoff

In [10]:
validate_matrices(WinRate_df, NumMatches_df)
win_rates = WinRate_df.to_numpy(dtype=float).ravel()
num_matches = NumMatches_df.to_numpy(dtype=float).ravel()
min_value, max_value = win_rates.min(), win_rates.max()
if min_value == max_value:
    raise ValueError("Cannot fit a KDE to constant win rates")
kde = gaussian_kde(win_rates, weights=num_matches)
total_cdf = kde.integrate_box_1d(min_value, max_value)
print(f"Win-rate range: {min_value:.2f}% to {max_value:.2f}%; KDE mass: {total_cdf:.6f}")

Win-rate range: 25.12% to 74.88%; KDE mass: 0.999893

In [11]:
utilities = {
    rate: round(2 * kde.integrate_box_1d(min_value, rate) / total_cdf - 1, 2)
    for rate in np.unique(win_rates)
}
payoff_values = np.array([utilities[rate] for rate in win_rates]).reshape(WinRate_df.shape)
Payoff_df = pd.DataFrame(payoff_values, index=WinRate_df.index, columns=WinRate_df.columns)
# Save the inputs used for this payoff so export can detect stale calculations.
payoff_input_rates = pd.DataFrame(win_rates.reshape(WinRate_df.shape), index=WinRate_df.index, columns=WinRate_df.columns)
payoff_input_counts = pd.DataFrame(num_matches.reshape(NumMatches_df.shape), index=NumMatches_df.index, columns=NumMatches_df.columns)
display(Payoff_df.head())

,Angela,Captain America,Deadpool Vanguard,Devil Dinosaur,Doctor Strange,Emma Frost,Groot,Hulk,Magneto,Peni Parker,...,Gambit,Invisible Woman,Jeff The Land Shark,Jubilee,Loki,Luna Snow,Mantis,Rocket Raccoon,Ultron,White Fox
Angela,-0.00,-0.52,0.45,-0.31,0.05,0.63,-0.64,-0.39,0.43,-1.00,...,0.16,0.71,0.42,0.25,-0.23,0.67,-0.67,-0.43,-0.91,0.59
Captain America,0.53,-0.00,0.88,-0.43,0.52,0.78,0.34,0.47,0.76,-0.98,...,0.61,0.75,0.74,0.56,-0.10,0.90,-0.14,0.10,-0.32,0.89
Deadpool Vanguard,-0.45,-0.88,-0.00,-0.93,-0.52,-0.28,-0.74,-0.85,0.00,-1.00,...,-0.48,-0.20,-0.06,-0.51,-0.83,0.14,-0.94,-0.83,-0.83,0.03
Devil Dinosaur,0.31,0.43,0.93,-0.00,0.76,0.94,0.87,0.12,0.91,-0.96,...,0.83,0.85,0.83,0.72,0.39,0.95,0.08,0.41,-0.04,0.92
Doctor Strange,-0.05,-0.52,0.52,-0.76,-0.00,0.38,0.03,-0.45,0.42,-0.99,...,0.20,0.19,0.17,0.28,-0.44,0.51,-0.72,-0.59,-0.74,0.54

## 10. Export all as CSVs

In [12]:
validate_matrices(WinRate_df, NumMatches_df)
if not (WinRate_df.astype(float).equals(payoff_input_rates)
        and NumMatches_df.astype(float).equals(payoff_input_counts)):
    raise ValueError("Matrices changed since payoff calculation; rerun both cells in section 9")
if (not Payoff_df.index.equals(WinRate_df.index)
        or not Payoff_df.columns.equals(WinRate_df.columns)
        or not np.isfinite(Payoff_df.to_numpy()).all()
        or (np.abs(Payoff_df.to_numpy()) > 1).any()):
    raise ValueError("Invalid payoff matrix; rerun section 9")

output_dir = Path(".")
output_dir.mkdir(parents=True, exist_ok=True)
for name, frame in (("WinRate", WinRate_df), ("NumMatches", NumMatches_df), ("Payoff", Payoff_df)):
    path = output_dir / f"MarvelRivals_{name}_Matrix.csv"
    frame.to_csv(path, index=True)
    print(f"Exported {path.resolve()}")

Exported /Users/xool/Library/CloudStorage/OneDrive-Personal/Jupyter WorkPlace/MATH441/Optimal_Rivalry/MarvelRivals_WinRate_Matrix.csv
Exported /Users/xool/Library/CloudStorage/OneDrive-Personal/Jupyter WorkPlace/MATH441/Optimal_Rivalry/MarvelRivals_NumMatches_Matrix.csv
Exported /Users/xool/Library/CloudStorage/OneDrive-Personal/Jupyter WorkPlace/MATH441/Optimal_Rivalry/MarvelRivals_Payoff_Matrix.csv